# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 989d5208d9d5e1b216406dfad8a1f48e3beee8549d7d630c9b52e01910d32d101abf9311fb3c5ea07d406e90027b8c6a30a02b994c99d80e08a0db8c2e602cb5

test:
  secret_key_base: 56c9098edaae5b6bb62f9072418c3a97938cd958eec21171cd8c374d9a171af26d67f50605489bb397f1f79f93807a567f05dea161a75c0da89ecb889b15400e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
